---
title: "Enricher_TNF/IL17_Normoxia"
output: html_document
date: "2022-10-21"
---

 Load packages

```{r}

library(clusterProfiler)
library(msigdbr)
library(tidyverse)
library(fgsea)
library(org.Hs.eg.db)
library(AnnotationDbi)

```
Load data

```{r}

model.results <-readxl::read_xlsx("downloads/Normoxia TNFandIL17vs Normoxia untreated .xlsx")
suppressMessages(model.results)

```

#Enrichment

Get gene set database
```{r}

H <- msigdbr::msigdbr(species = "Homo sapiens", category = "H")
H
#class(H)

```

Define significant genes
```{r}
model.results$log2FoldChange <- as.numeric(model.results$log2FoldChange)
signif <- model.results %>%
  filter(abs(log2FoldChange) >= 1)
```

Get gene name
```{r}
#signif.ensembl <- unique(signif$ensembl_gene_id)
#H.ensembl <- dplyr::select(H, gs_name, ensembl_gene)

signif.name <- unique(signif$gene_name)
H.name <- dplyr::select(H, gs_name, gene_symbol)

```

Run enrichment
```{r}

#enrich.H <- enricher(gene = signif.ensembl, TERM2GENE = H.ensembl)

enrich.H <- enricher(gene = signif.name, TERM2GENE = H.name)

fit <- plot(barplot(enrich.H, showCategory = 10, title = "HALLMARK gene set"))

```
ORA with GO biological pathways
```{r}

GO_results <- enrichGO(gene = signif.name, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", ont = "BP")

as.data.frame(GO_results)

```

```{r}

fit <- plot(barplot(GO_results, showCategory = 10, title = "GO biological pathways"))
#png("GO_analysis.png", res= 250, width = 1200, height = 1000)
#print(fit)
#dev.off()
#fit
```
Convert Ensembl to Entrez
```{r}
#columns(org.Hs.eg.db) # returns list of available keytypes

signif$entrez = mapIds(org.Hs.eg.db, keys = signif$gene_name,  column="ENTREZID",keytype="SYMBOL",multiVals="first")

```

ORA with KEGG
```{r}

signif.entrez <- unique(signif$entrez)
KEGG_results <- enrichKEGG(gene = signif.entrez, organism = "hsa" ,keyType = "ncbi-geneid")
as.data.frame(KEGG_results)


fit <- plot(barplot(KEGG_results, showCategory = 10, title = "KEGG pathways"))
```
Gene set enrichment analysis (GSEA)

GSEA: Prepare inputs
```{r}
# we want the log2 fold change 
original_gene_list <- model.results$log2FoldChange

# name the vector
names(original_gene_list) <- model.results$gene_id

# omit any NA values 
gene_list <- na.omit(original_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
gene_list = sort(gene_list, decreasing = TRUE)



```

GO enrichment analysis
```{r}
gse <- gseGO(geneList = gene_list, ont = "BP", 
             keyType ="ENSEMBL", 
             nPerm = 10000, 
             minGSSize = 3, 
             maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = "org.Hs.eg.db", 
             pAdjustMethod = "none")

    

```

OUTPUT
```{r}
require(DOSE)
dotplot(gse, showCategory=3, split=".sign", title = "GO biological pathways") + facet_grid(.~.sign)

```
GSEA KEGG: Prepare input
```{r}

# Convert gene IDs for gseKEGG function
# We will lose some genes here because not all IDs will be converted
ids<- bitr(names(original_gene_list), fromType = "ENSEMBL", toType = "ENTREZID", OrgDb= "org.Hs.eg.db")
 # remove duplicate IDS (here I use "ENSEMBL", but it should be whatever was selected as keyType)
dedup_ids = ids[!duplicated(ids[c("ENSEMBL")]),]

# Create a new dataframe df2 which has only the genes which were successfully mapped using the bitr function above
df2 = model.results[model.results$gene_id %in% dedup_ids$ENSEMBL,]

# Create a new column in df2 with the corresponding ENTREZ IDs
df2$Y = dedup_ids$ENTREZID

# Create a vector of the gene unuiverse
kegg_gene_list <- df2$log2FoldChange

# Name vector with ENTREZ ids
names(kegg_gene_list) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)


```

GSEA KEGG
```{r}
kk2 <- gseKEGG(geneList     = kegg_gene_list,
               organism     = "hsa",
               nPerm        = 10000,
               minGSSize    = 3,
               maxGSSize    = 800,
               pvalueCutoff = 0.05,
               pAdjustMethod = "none",
               keyType       = "ncbi-geneid")
```

```{r}
dotplot(kk2, showCategory = 2
        , title = "KEGG Pathways" , split=".sign") + facet_grid(.~.sign)

```